### ISSUE TITLE
Add better UX Design when logging in/creating an account, plus other UX issues. 

### ISSUE THREAD

**Issue by EdgarQuinones** [Geo-Bold/link-share#1]
-When I tried to log in or make an account nothing happened. No error or success. I think there needs to be more output to the user so they know what's happening
- The login button still says login after I have logged in.
- In preview page I get confused how to go back

**Comment by Geo-Bold** [comment]
This issue has been fixed in commit [d818de](https://github.com/Geo-Bold/link-share/commit/d818de2f9eb3f4a45ba4c8b5e07b46ff425f60b6).
