### ISSUE TITLE
Navigating to customize your links page after viewing someone else's profile gives shared user's links as their own

### ISSUE THREAD

**Issue by anthonyisensee** [Geo-Bold/link-share#2]
If you're hoping to convert visitors to other people's profiles into users of devlinks themselves I don't think it makes sense that clicking the devlinks logo from viewing someone else's links would populate the "Customize your links" window with the links of the user whose link page they were just visiting. See the attached video for an example.

https://github.com/user-attachments/assets/edc86cf2-e502-4ebd-8795-b178741a2eff

Also, consider learning how to link and close this issue to a commit using your commit message ("fix: xyz, resolves #2", [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)).

**Comment by Geo-Bold** [comment]
That's why you're the goat! @anthonyisensee

**Comment by Geo-Bold** [comment]
That's why you're the goat! @anthonyisensee Great find, I thought no one would notice.
